import Link from 'next/link';
import { publicMetadata } from '../lib/site';
export const metadata = publicMetadata('/privacidad', 'Privacidad — Atlas del Cultivo Argentino', 'Qué información guarda el Atlas y cómo descargar o eliminar tus datos.');
export default function Page() {
  return <main className="atlas-page"><section className="atlas-category-hero"><div><span className="section-label dark-label">Tus datos</span><h1>Privacidad</h1><p className="atlas-lede">Podés leer y buscar en el Atlas sin crear una cuenta. La cuenta permite guardar tu seguimiento de cultivo y acceder a los paneles de club o administración según tu rol.</p></div></section><article className="atlas-section privacy-copy">
    <h2>Exploración y lecturas</h2><p>La provincia, la zona elegida, las lecturas guardadas y tu última posición de lectura quedan en el almacenamiento de este navegador. Podés quitar la provincia desde el Atlas y las lecturas desde Guardadas. Al borrar los datos del sitio en el navegador se eliminan estas preferencias.</p>
    <h2>Mi Cultivo</h2><p>Si usás la bitácora local, queda en este dispositivo. Con cuenta, Supabase guarda el email, el perfil, las temporadas, las plantas, los eventos, las notas, las fotos y las preferencias de notificación. El acceso a los registros de cultivo está limitado a la cuenta que los creó.</p><p>Las fotos se procesan antes de subirlas para reducir su tamaño y quitar metadatos del archivo, incluida la información EXIF. Se guardan en un depósito privado y se consultan mediante enlaces temporales.</p>
    <h2>Ubicación y clima</h2><p>Elegís la ubicación de forma manual y aproximada. El Atlas no solicita GPS ni dirección exacta. El servicio meteorológico consulta un punto de referencia de la provincia; no recibe la ubicación de tu cultivo. Las zonas de navegación no cambian ese pronóstico.</p>
    <h2>Sesión y proveedores</h2><p>Supabase gestiona el ingreso y utiliza cookies para mantener la sesión. Si ingresás con Google, ese proveedor interviene en la autenticación. El alojamiento y los servicios externos pueden registrar información técnica de las solicitudes, como la dirección IP.</p>
    <h2>Aportes y correcciones</h2><p>El equipo guarda el mensaje, su referencia y el email opcional en una bandeja privada. Se usan para revisar el aporte y responderte. Para limitar envíos repetidos, se genera un identificador diario a partir de la conexión; el formulario no guarda la dirección IP sin transformar.</p>
    <h2>Descargar o eliminar</h2><p>En Mi Cultivo → Ajustes podés descargar tus registros. Con cuenta, el archivo incluye todas tus temporadas y las fotos codificadas en su interior. También podés eliminar tu cuenta y sus datos asociados, incluidas las fotos del depósito privado. Los registros administrativos y los mensajes enviados como aportes se gestionan por separado.</p><p>La eliminación de la cuenta no borra automáticamente las preferencias de otros navegadores ni las copias que hayas descargado. Para pedir una corrección o eliminación de un aporte, usá el formulario e indicá su referencia.</p>
    <div className="mi-cultivo-form-actions"><Link className="primary-button" href="/mi-cultivo">Ir a Mi Cultivo</Link><Link className="secondary-button" href="/aportes">Contactar al equipo</Link></div>
  </article></main>;
}
