// Photographic locations verified against each Commons file description.
// Licenses apply to the images; attribution is rendered with every card.
export const PROVINCE_PHOTOS = [
  { provinceId: 'jujuy', region: 'noa', name: 'Jujuy', place: 'Quebrada de Humahuaca', image: '/atlas/field/province-jujuy.webp', alt: 'Formaciones de roca y laderas de la Quebrada de Humahuaca, Jujuy', author: 'Idobi', source: 'https://commons.wikimedia.org/wiki/File:QuebradadeHumahuaca02.jpg', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/' },
  { provinceId: 'misiones', region: 'nea', name: 'Misiones', place: 'Cataratas del Iguazú', image: '/atlas/field/province-misiones.webp', alt: 'Cataratas rodeadas de selva en Iguazú, Misiones', author: 'Emesbe', source: 'https://commons.wikimedia.org/wiki/File:Iguazu_Falls.jpg', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/' },
  { provinceId: 'mendoza', region: 'cuyo', name: 'Mendoza', place: 'Aconcagua', image: '/atlas/field/province-mendoza.webp', alt: 'Cumbre nevada del Aconcagua y laderas de montaña en Mendoza', author: 'Guritxu', source: 'https://commons.wikimedia.org/wiki/File:Aconcagua._Parque_Nacional.jpg', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/' },
  { provinceId: 'buenos-aires', region: 'pampeana', name: 'Buenos Aires', place: 'Sierras de Ventania', image: '/atlas/field/province-buenos-aires.webp', alt: 'Pastizales y rocas de las sierras de Ventania, Buenos Aires', author: '.vxctoria', source: 'https://commons.wikimedia.org/wiki/File:Rock_formations_in_Sierra_de_la_Ventana.jpg', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/' },
  { provinceId: 'rionegro', region: 'patagonia', name: 'Río Negro', place: 'Península Llao Llao', image: '/atlas/field/patagonia-llao-llao.webp', alt: 'Bosques, montañas y lagos de la península Llao Llao, Río Negro', author: 'Fernando', source: 'https://commons.wikimedia.org/wiki/File:Llao_Llao_Peninsula_Panorama.jpg', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/' },
];
