// Excepción autorizada por el usuario: tres ilustraciones originales, identificadas como IA.
export const generatedVisuals = [
  {
    "id": "asset-generated-super-cropping",
    "file": "/atlas/entries/generated/super-cropping.webp",
    "type": "illustration",
    "categoryId": null,
    "entryId": "super-cropping",
    "sourceId": null,
    "sourceUrl": null,
    "author": "Atlas del Cultivo Argentino",
    "license": "Interno",
    "generated": true,
    "generationTool": "image_gen",
    "createdAt": "2026-10-06",
    "width": 1400,
    "height": 933,
    "alt": "Ilustración de una rama de Cannabis flexionada, con hojas y tallo intacto.",
    "caption": "Representación conceptual de una rama flexionada. Ilustración generada con IA; no es una observación experimental ni una guía del procedimiento.",
    "credit": "Ilustración original para el Atlas · Generada con IA.",
    "status": "ACTIVE",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte.",
    "knownIssues": "Creada por solicitud explícita del usuario para esta entrada. Es una ilustración conceptual, no una fotografía documental, evidencia científica, afiche oficial o fotograma."
  },
  {
    "id": "asset-generated-documental-madre-planta",
    "file": "/atlas/entries/generated/documental-madre-planta.webp",
    "type": "illustration",
    "categoryId": null,
    "entryId": "documental-madre-planta",
    "sourceId": null,
    "sourceUrl": null,
    "author": "Atlas del Cultivo Argentino",
    "license": "Interno",
    "generated": true,
    "generationTool": "image_gen",
    "createdAt": "2026-10-06",
    "width": 1400,
    "height": 933,
    "alt": "Ilustración de manos de dos generaciones que cuidan una planta de Cannabis en una maceta.",
    "caption": "Cuidado compartido y cultivo doméstico. Ilustración editorial generada con IA para la reseña de Madre Planta, con personajes anónimos.",
    "credit": "Ilustración original para el Atlas · Generada con IA.",
    "status": "ACTIVE",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte.",
    "knownIssues": "Creada por solicitud explícita del usuario para esta entrada. Es una ilustración conceptual, no una fotografía documental, evidencia científica, afiche oficial o fotograma."
  },
  {
    "id": "asset-generated-documental-el-profe",
    "file": "/atlas/entries/generated/documental-el-profe.webp",
    "type": "illustration",
    "categoryId": null,
    "entryId": "documental-el-profe",
    "sourceId": null,
    "sourceUrl": null,
    "author": "Atlas del Cultivo Argentino",
    "license": "Interno",
    "generated": true,
    "generationTool": "image_gen",
    "createdAt": "2026-10-06",
    "width": 1400,
    "height": 933,
    "alt": "Ilustración de un encuentro de aprendizaje junto a una planta de Cannabis y un cuaderno de observaciones.",
    "caption": "Aprender y compartir conocimientos de cultivo. Ilustración editorial generada con IA para la reseña de El Profe, con personajes anónimos.",
    "credit": "Ilustración original para el Atlas · Generada con IA.",
    "status": "ACTIVE",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte.",
    "knownIssues": "Creada por solicitud explícita del usuario para esta entrada. Es una ilustración conceptual, no una fotografía documental, evidencia científica, afiche oficial o fotograma."
  }
];
