// Fuentes y licencias verificadas en los repositorios originales el 2026-10-06.
// Un archivo puede ilustrar varias entradas sin duplicar la atribución.
export const openVisuals = [
  {
    "id": "asset-open-poda-experimento",
    "file": "/atlas/entries/commons/poda-experimento.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "poda-de-bajos-bblr",
      "defoliacion",
      "arquitectura-y-asignacion-de-recursos"
    ],
    "sourceId": "visual-open-poda-experimento",
    "author": "Nadav Danziger y Nirit Bernstein",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "sourceUrl": "https://www.mdpi.com/2223-7747/10/9/1834",
    "originalUrl": "https://mdpi-res.com/d_attachment/plants/plants-10-01834/article_deploy/html/images/plants-10-01834-g001.png",
    "alt": "Aspecto de plantas de Cannabis con distintos tratamientos de manejo de su arquitectura. La figura compara, entre otros, defoliación y retiro de hojas y ramas de la parte baja (BBLR). Figura 1 de Danziger y Bernstein (2021).",
    "caption": "Aspecto de plantas de Cannabis con distintos tratamientos de manejo de su arquitectura. La figura compara, entre otros, defoliación y retiro de hojas y ramas de la parte baja (BBLR). Figura 1 de Danziger y Bernstein (2021).",
    "credit": "Nadav Danziger y Nirit Bernstein · CC BY 4.0 · Plants / MDPI",
    "width": 1600,
    "height": 407,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-tricomas",
    "file": "/atlas/entries/commons/tricomas.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "quimica-de-la-maduracion",
      "cosecha-y-maduracion",
      "fertilizacion-y-cannabinoides-evidencia"
    ],
    "sourceId": "visual-open-tricomas",
    "author": "Cannabis Pictures",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cannabis_Trichomes_(17300377912).jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/4/44/Cannabis_Trichomes_%2817300377912%29.jpg",
    "alt": "Detalle de tricomas de Cannabis. La fotografía muestra su estructura; no permite determinar por sí sola la composición química ni el punto de cosecha.",
    "caption": "Detalle de tricomas de Cannabis. La fotografía muestra su estructura; no permite determinar por sí sola la composición química ni el punto de cosecha.",
    "credit": "Cannabis Pictures · CC BY 2.0 · Wikimedia Commons",
    "width": 1200,
    "height": 675,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-belgrano",
    "file": "/atlas/entries/commons/belgrano.webp",
    "type": "illustration",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "historia-de-la-planta-argentina"
    ],
    "sourceId": "visual-open-belgrano",
    "author": "Attributed to Casimir Carbonnier",
    "license": "Dominio público",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Manuel_belgrano_by_carbonier_retouched.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/8/81/Manuel_belgrano_by_carbonier_retouched.jpg",
    "alt": "Retrato de Manuel Belgrano, atribuido a Casimir Carbonnier (1815). Belgrano promovió el cultivo del cáñamo en el Río de la Plata.",
    "caption": "Retrato de Manuel Belgrano, atribuido a Casimir Carbonnier (1815). Belgrano promovió el cultivo del cáñamo en el Río de la Plata.",
    "credit": "Attributed to Casimir Carbonnier · Public domain · Wikimedia Commons",
    "width": 1200,
    "height": 1455,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-division-celular",
    "file": "/atlas/entries/commons/division-celular.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "division-celular-elongacion-diferenciacion"
    ],
    "sourceId": "visual-open-division-celular",
    "author": "Doc. RNDr. Josef Reischig, CSc.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Metaphase_(261_06)_Pressed;_meristem_of_root;_onion.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/1/18/Metaphase_%28261_06%29_Pressed%3B_meristem_of_root%3B_onion.jpg",
    "alt": "Células de un meristemo de raíz de cebolla observadas al microscopio. Ejemplo general de división celular vegetal; no corresponde a Cannabis.",
    "caption": "Células de un meristemo de raíz de cebolla observadas al microscopio. Ejemplo general de división celular vegetal; no corresponde a Cannabis.",
    "credit": "Doc. RNDr. Josef Reischig, CSc. · CC BY-SA 3.0 · Wikimedia Commons",
    "width": 1200,
    "height": 768,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-meristemo",
    "file": "/atlas/entries/commons/meristemo.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "meristemos-crecimiento-primario-secundario"
    ],
    "sourceId": "visual-open-meristemo",
    "author": "Naz Amann",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Root_Apical_Meristem_cell.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Root_Apical_Meristem_cell.jpg",
    "alt": "Micrografía del meristemo apical de una raíz. Ilustra una zona de división celular en plantas; la fuente no la identifica como Cannabis.",
    "caption": "Micrografía del meristemo apical de una raíz. Ilustra una zona de división celular en plantas; la fuente no la identifica como Cannabis.",
    "credit": "Naz Amann · CC BY 4.0 · Wikimedia Commons",
    "width": 1200,
    "height": 1139,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-turgencia",
    "file": "/atlas/entries/commons/turgencia.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "agua-y-expansion-celular",
      "estres-ambiental-y-crecimiento"
    ],
    "sourceId": "visual-open-turgencia",
    "author": "LadyofHats",
    "license": "Dominio público",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Turgor_pressure_on_plant_cells_diagram.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Turgor_pressure_on_plant_cells_diagram.svg",
    "alt": "Esquema general de la relación entre agua, vacuola y turgencia celular. No representa una medición de Cannabis.",
    "caption": "Esquema general de la relación entre agua, vacuola y turgencia celular. No representa una medición de Cannabis.",
    "credit": "LadyofHats · Public domain · Wikimedia Commons",
    "width": 1600,
    "height": 633,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-fotosintesis",
    "file": "/atlas/entries/commons/fotosintesis.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "fotosintesis-respiracion-y-biomasa"
    ],
    "sourceId": "visual-open-fotosintesis",
    "author": "At09kg , Wattcle , Nefronus At09kg : original Wattcle : vector graphics Nefronus : redoing the vector graphics",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Photosynthesis_en.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/5/55/Photosynthesis_en.svg",
    "alt": "Esquema general de fotosíntesis: entrada de luz, agua y dióxido de carbono, y producción de azúcares y oxígeno. Rótulos originales en inglés.",
    "caption": "Esquema general de fotosíntesis: entrada de luz, agua y dióxido de carbono, y producción de azúcares y oxígeno. Rótulos originales en inglés.",
    "credit": "At09kg , Wattcle , Nefronus At09kg : original Wattcle : vector graphics Nefronus : redoing the vector graphics · CC BY-SA 4.0 · Wikimedia Commons",
    "width": 1600,
    "height": 1600,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-floracion",
    "file": "/atlas/entries/commons/floracion.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "elongacion-stretch-floracion",
      "variacion-genetica-fotoperiodo",
      "nutricion-de-cannabis-variacion-genotipica"
    ],
    "sourceId": "visual-open-floracion",
    "author": "My 420 Tours",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Flowering_cannabis_plant.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flowering_cannabis_plant.jpg",
    "alt": "Planta de Cannabis en floración. La fotografía documenta su porte y sus inflorescencias; no identifica un genotipo ni permite medir su respuesta al fotoperíodo.",
    "caption": "Planta de Cannabis en floración. La fotografía documenta su porte y sus inflorescencias; no identifica un genotipo ni permite medir su respuesta al fotoperíodo.",
    "credit": "My 420 Tours · CC BY-SA 4.0 · Wikimedia Commons",
    "width": 1200,
    "height": 900,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-suelo-perfil",
    "file": "/atlas/entries/commons/suelo-perfil.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "evaluacion-visual-del-suelo",
      "lectura-guia-evaluacion-visual-suelo"
    ],
    "sourceId": "visual-open-suelo-perfil",
    "author": "Cjrufe",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Soil_Profile_Containing_an_Argillic_Horizon.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/8/82/Soil_Profile_Containing_an_Argillic_Horizon.jpg",
    "alt": "Perfil de suelo con un horizonte de acumulación de arcilla. Ejemplo de observación de horizontes; no es una imagen de la guía reseñada ni de un suelo argentino.",
    "caption": "Perfil de suelo con un horizonte de acumulación de arcilla. Ejemplo de observación de horizontes; no es una imagen de la guía reseñada ni de un suelo argentino.",
    "credit": "Cjrufe · CC0 · Wikimedia Commons",
    "width": 1125,
    "height": 1500,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-textura-suelo",
    "file": "/atlas/entries/commons/textura-suelo.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "textura-estructura-porosidad"
    ],
    "sourceId": "visual-open-textura-suelo",
    "author": "USDA Soil Survey Division Staff",
    "license": "Dominio público",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:SoilTextureTriangle.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/3/39/SoilTextureTriangle.svg",
    "alt": "Triángulo textural del USDA: clasificación del suelo según sus porcentajes de arena, limo y arcilla. Rótulos originales en inglés.",
    "caption": "Triángulo textural del USDA: clasificación del suelo según sus porcentajes de arena, limo y arcilla. Rótulos originales en inglés.",
    "credit": "USDA Soil Survey Division Staff · Public domain · Wikimedia Commons",
    "width": 1558,
    "height": 1800,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-retencion-agua",
    "file": "/atlas/entries/commons/retencion-agua.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "capacidad-de-campo-agua-disponible"
    ],
    "sourceId": "visual-open-retencion-agua",
    "author": "Giancarlo Dessì",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Water_retention_curve_clay-it.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/8/88/Water_retention_curve_clay-it.svg",
    "alt": "Curva general de retención de agua en suelo arcilloso. Rótulos originales en italiano; no es una curva medida para un sustrato de Cannabis.",
    "caption": "Curva general de retención de agua en suelo arcilloso. Rótulos originales en italiano; no es una curva medida para un sustrato de Cannabis.",
    "credit": "Giancarlo Dessì · CC BY-SA 3.0 · Wikimedia Commons",
    "width": 1600,
    "height": 1600,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-compost",
    "file": "/atlas/entries/commons/compost.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "materia-organica-actividad-biologica",
      "nutricion-organica-y-mineral"
    ],
    "sourceId": "visual-open-compost",
    "author": "Autor no identificado en la ficha original",
    "license": "Dominio público",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Compost.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f5/Compost.jpg",
    "alt": "Compost: material orgánico transformado. La imagen muestra su aspecto, sin certificar su composición ni su madurez.",
    "caption": "Compost: material orgánico transformado. La imagen muestra su aspecto, sin certificar su composición ni su madurez.",
    "credit": "Autor no identificado en la ficha original · Public domain · Wikimedia Commons",
    "width": 640,
    "height": 434,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-micorrizas",
    "file": "/atlas/entries/commons/micorrizas.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "suelo-vivo-y-microbiologia"
    ],
    "sourceId": "visual-open-micorrizas",
    "author": "Vojtech.dostal; traducción de Edward the Confessor; ajuste de rótulos de Polinizador",
    "license": "Dominio público",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:485px-Arbuscular_mycorrhiza_cross-section-es.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2d/485px-Arbuscular_mycorrhiza_cross-section-es.jpg",
    "alt": "Esquema de una micorriza arbuscular y su relación con las células de la raíz. Ilustración general con rótulos en español.",
    "caption": "Esquema de una micorriza arbuscular y su relación con las células de la raíz. Ilustración general con rótulos en español.",
    "credit": "Vojtech.dostal; traducción de Edward the Confessor; ajuste de rótulos de Polinizador · Public domain · Wikimedia Commons",
    "width": 485,
    "height": 600,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-salinizacion",
    "file": "/atlas/entries/commons/salinizacion.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "conductividad-electrica-y-sales",
      "calidad-del-agua-de-riego"
    ],
    "sourceId": "visual-open-salinizacion",
    "author": "Dreamcabbage",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Soil_Salinization_Color.png",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f9/Soil_Salinization_Color.png",
    "alt": "Esquema general de salinización del suelo por riego y evaporación. No indica umbrales de conductividad para Cannabis.",
    "caption": "Esquema general de salinización del suelo por riego y evaporación. No indica umbrales de conductividad para Cannabis.",
    "credit": "Dreamcabbage · CC0 · Wikimedia Commons",
    "width": 1600,
    "height": 1085,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-espectro-visible",
    "file": "/atlas/entries/commons/espectro-visible.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "espectro-de-luz-azul-rojo-rojo-lejano",
      "par-ppfd-medicion-de-luz"
    ],
    "sourceId": "visual-open-espectro-visible",
    "author": "Original: Daniele Pugliesi Vector: M0tty",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chlorophyll_ab_spectra-en.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/2/23/Chlorophyll_ab_spectra-en.svg",
    "alt": "Espectros de absorción de las clorofilas a y b según la longitud de onda. Diagrama general de pigmentos vegetales; no representa una medición de PPFD ni la respuesta de una planta entera.",
    "caption": "Espectros de absorción de las clorofilas a y b según la longitud de onda. Diagrama general de pigmentos vegetales; no representa una medición de PPFD ni la respuesta de una planta entera.",
    "credit": "Original: Daniele Pugliesi Vector: M0tty · CC BY-SA 3.0 · Wikimedia Commons",
    "width": 1280,
    "height": 1280,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-espectro-electromagnetico",
    "file": "/atlas/entries/commons/espectro-electromagnetico.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "radiacion-uv-y-cannabinoides"
    ],
    "sourceId": "visual-open-espectro-electromagnetico",
    "author": "Horst Frank , Jailbird",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Electromagnetic_spectrum-es.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Electromagnetic_spectrum-es.svg",
    "alt": "Espectro electromagnético con la ubicación de la radiación ultravioleta y la luz visible. No representa un efecto medido sobre cannabinoides.",
    "caption": "Espectro electromagnético con la ubicación de la radiación ultravioleta y la luz visible. No representa un efecto medido sobre cannabinoides.",
    "credit": "Horst Frank , Jailbird · CC BY-SA 3.0 · Wikimedia Commons",
    "width": 1600,
    "height": 490,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-helada",
    "file": "/atlas/entries/commons/helada.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "heladas"
    ],
    "sourceId": "visual-open-helada",
    "author": "Tord Dellsen",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leaf_with_frost_2.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Leaf_with_frost_2.jpg",
    "alt": "Escarcha sobre una hoja. Ejemplo general de congelación superficial; la hoja fotografiada no es Cannabis.",
    "caption": "Escarcha sobre una hoja. Ejemplo general de congelación superficial; la hoja fotografiada no es Cannabis.",
    "credit": "Tord Dellsen · CC0 · Wikimedia Commons",
    "width": 1200,
    "height": 1200,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-estomas",
    "file": "/atlas/entries/commons/estomas.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "humedad-relativa-transpiracion-vpd"
    ],
    "sourceId": "visual-open-estomas",
    "author": "Trương Minh Khải",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Stomata_of_Tradescantia_spathacea_leaves.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Stomata_of_Tradescantia_spathacea_leaves.jpg",
    "alt": "Estomas de una hoja de Tradescantia spathacea observados al microscopio a 400 aumentos. Ejemplo general de estructuras que regulan el intercambio de gases y la pérdida de agua; no corresponde a Cannabis.",
    "caption": "Estomas de una hoja de Tradescantia spathacea observados al microscopio a 400 aumentos. Ejemplo general de estructuras que regulan el intercambio de gases y la pérdida de agua; no corresponde a Cannabis.",
    "credit": "Trương Minh Khải · CC BY 4.0 · Wikimedia Commons",
    "width": 1200,
    "height": 1197,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-clima-argentina",
    "file": "/atlas/entries/commons/clima-argentina.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "aptitud-agroclimatica-argentina-canamo",
      "diferencias-agroclimaticas-regiones-argentinas"
    ],
    "sourceId": "visual-open-clima-argentina",
    "author": "Beck, H.E., McVicar, T.R., Vergopolan, N., Alexis, B., Lutsko, N.J., Dufour, A., Zeng, Z., Jian, X., van Dijk, A.I.J.M., Miralles, D.G.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Koppen-Geiger_Map_v2_ARG_1991%E2%80%932020.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/6/65/Koppen-Geiger_Map_v2_ARG_1991%E2%80%932020.svg",
    "alt": "Clasificación climática Köppen–Geiger de Argentina para 1991–2020, a partir de Beck y colaboradores. Describe climas; no es un mapa de aptitud de cultivo.",
    "caption": "Clasificación climática Köppen–Geiger de Argentina para 1991–2020, a partir de Beck y colaboradores. Describe climas; no es un mapa de aptitud de cultivo.",
    "credit": "Beck, H.E., McVicar, T.R., Vergopolan, N., Alexis, B., Lutsko, N.J., Dufour, A., Zeng, Z., Jian, X., van Dijk, A.I.J.M., Miralles, D.G. · CC BY 4.0 · Wikimedia Commons",
    "width": 1280,
    "height": 852,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-damping-off",
    "file": "/atlas/entries/commons/damping-off.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "chupadera-fungosa-damping-off"
    ],
    "sourceId": "visual-open-damping-off",
    "author": "INAKAvillage211",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pinus_taeda_seedling_damping_off.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Pinus_taeda_seedling_damping_off.jpg",
    "alt": "Plántula de Pinus taeda afectada por damping-off. Ejemplo documentado en pino; no debe interpretarse como una fotografía de Cannabis enferma.",
    "caption": "Plántula de Pinus taeda afectada por damping-off. Ejemplo documentado en pino; no debe interpretarse como una fotografía de Cannabis enferma.",
    "credit": "INAKAvillage211 · CC BY-SA 3.0 · Wikimedia Commons",
    "width": 500,
    "height": 331,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-hongos-cannabis",
    "file": "/atlas/entries/commons/hongos-cannabis.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "moho-gris-botrytis-cinerea"
    ],
    "sourceId": "visual-open-hongos-cannabis",
    "author": "Kimberly D Gwinn, Maxwell C K Leung, Ariell B Stephens, and Zamir K Punja",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fungal_Pathogens,_Epiphytes,_and_Endophytes_Affecting_Cannabis_Inflorescences.png",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/a/af/Fungal_Pathogens%2C_Epiphytes%2C_and_Endophytes_Affecting_Cannabis_Inflorescences.png",
    "alt": "Lámina científica de hongos asociados a inflorescencias de Cannabis. El panel C muestra daño por Botrytis cinerea; los demás paneles documentan otros hongos y síntomas.",
    "caption": "Lámina científica de hongos asociados a inflorescencias de Cannabis. El panel C muestra daño por Botrytis cinerea; los demás paneles documentan otros hongos y síntomas.",
    "credit": "Kimberly D Gwinn, Maxwell C K Leung, Ariell B Stephens, and Zamir K Punja · CC BY 4.0 · Wikimedia Commons",
    "width": 1280,
    "height": 1747,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-hidroponia",
    "file": "/atlas/entries/commons/hidroponia.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "interior-y-exterior",
      "nutricion-suelo-sustrato-hidroponia",
      "intensidad-de-luz"
    ],
    "sourceId": "visual-open-hidroponia",
    "author": "Plantlady223",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Two_hydroponic_cannabis_plants.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Two_hydroponic_cannabis_plants.jpg",
    "alt": "Dos plantas de Cannabis en un sistema hidropónico de interior. La foto muestra el montaje, sin aportar mediciones de intensidad luminosa.",
    "caption": "Dos plantas de Cannabis en un sistema hidropónico de interior. La foto muestra el montaje, sin aportar mediciones de intensidad luminosa.",
    "credit": "Plantlady223 · CC BY-SA 4.0 · Wikimedia Commons",
    "width": 1200,
    "height": 900,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-tijeras",
    "file": "/atlas/entries/commons/tijeras.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "herramientas-e-higiene-de-poda"
    ],
    "sourceId": "visual-open-tijeras",
    "author": "barockschloss from Zeilitzheim, Germany",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pruning_shears.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/1/15/Pruning_shears.jpg",
    "alt": "Tijera de poda. La imagen identifica la herramienta; no documenta un procedimiento de limpieza o desinfección.",
    "caption": "Tijera de poda. La imagen identifica la herramienta; no documenta un procedimiento de limpieza o desinfección.",
    "credit": "barockschloss from Zeilitzheim, Germany · CC BY 2.0 · Wikimedia Commons",
    "width": 500,
    "height": 500,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-ph-nutrientes",
    "file": "/atlas/entries/commons/ph-nutrientes.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "ph-y-disponibilidad-de-nutrientes",
      "interacciones-antagonismos-nutricionales"
    ],
    "sourceId": "visual-open-ph-nutrientes",
    "author": "CoolKoon",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Soil_pH_effect_on_nutrient_availability.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Soil_pH_effect_on_nutrient_availability.svg",
    "alt": "Esquema general de disponibilidad de elementos en el suelo según el pH. No es una receta de pH ni una medición de antagonismos en Cannabis.",
    "caption": "Esquema general de disponibilidad de elementos en el suelo según el pH. No es una receta de pH ni una medición de antagonismos en Cannabis.",
    "credit": "CoolKoon · CC BY 4.0 · Wikimedia Commons",
    "width": 1280,
    "height": 1121,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-tabla-periodica",
    "file": "/atlas/entries/commons/tabla-periodica.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "elementos-esenciales-criterios-clasificacion",
      "calcio-magnesio-azufre-funcion-movilidad",
      "micronutrientes-funciones",
      "silicio-y-elementos-beneficiosos"
    ],
    "sourceId": "visual-open-tabla-periodica",
    "author": "2012rc",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Periodic_table_large.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4d/Periodic_table_large.svg",
    "alt": "Tabla periódica de los elementos. Permite ubicar sus símbolos químicos; no distingue por sí sola nutrientes esenciales, movilidad ni dosis para plantas.",
    "caption": "Tabla periódica de los elementos. Permite ubicar sus símbolos químicos; no distingue por sí sola nutrientes esenciales, movilidad ni dosis para plantas.",
    "credit": "2012rc · CC BY 3.0 · Wikimedia Commons",
    "width": 1600,
    "height": 944,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-nitrogeno",
    "file": "/atlas/entries/commons/nitrogeno.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "nitrogeno-fosforo-potasio-funcion"
    ],
    "sourceId": "visual-open-nitrogeno",
    "author": "Cicle_del_nitrogen_de.svg : * Cicle_del_nitrogen_ca.svg : Johann Dréo ( User:Nojhan ), traduction de Joanjoc d'après Image:Cycle azote fr.svg . derivative work: Burkhard ( talk ) Nitrogen_Cycle.jpg : Environmental Protection Agency derivative work: Raeky ( talk )",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nitrogen_Cycle.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/f/fe/Nitrogen_Cycle.svg",
    "alt": "Ciclo general del nitrógeno en el ambiente. La figura se refiere al nitrógeno, no describe los ciclos del fósforo o del potasio.",
    "caption": "Ciclo general del nitrógeno en el ambiente. La figura se refiere al nitrógeno, no describe los ciclos del fósforo o del potasio.",
    "credit": "Cicle_del_nitrogen_de.svg : * Cicle_del_nitrogen_ca.svg : Johann Dréo ( User:Nojhan ), traduction de Joanjoc d'après Image:Cycle azote fr.svg . derivative work: Burkhard ( talk ) Nitrogen_Cycle.jpg : Environmental Protection Agency derivative work: Raeky ( talk ) · CC BY-SA 3.0 · Wikimedia Commons",
    "width": 1280,
    "height": 960,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-raices",
    "file": "/atlas/entries/commons/raices.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "como-llegan-nutrientes-a-la-raiz",
      "arquitectura-y-asignacion-de-recursos"
    ],
    "sourceId": "visual-open-raices",
    "author": "Beeblebrox",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Root_ball.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e1/Root_ball.jpg",
    "alt": "Sistema de raíces de Cannabis cultivada en hidroponía. Permite observar la arquitectura de la raíz; no mide absorción de nutrientes.",
    "caption": "Sistema de raíces de Cannabis cultivada en hidroponía. Permite observar la arquitectura de la raíz; no mide absorción de nutrientes.",
    "credit": "Beeblebrox · CC BY-SA 4.0 · Wikimedia Commons",
    "width": 1200,
    "height": 900,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-thc",
    "file": "/atlas/entries/commons/thc.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "lectura-starks-marijuana-potency",
      "canamo-industrial-frontera-thc"
    ],
    "sourceId": "visual-open-thc",
    "author": "Harbin",
    "license": "Dominio público",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:THC.svg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/d/d1/THC.svg",
    "alt": "Estructura química del THC. Imagen de referencia del compuesto; no es la portada de un libro ni permite determinar el contenido de THC de una planta.",
    "caption": "Estructura química del THC. Imagen de referencia del compuesto; no es la portada de un libro ni permite determinar el contenido de THC de una planta.",
    "credit": "Harbin · Public domain · Wikimedia Commons",
    "width": 1280,
    "height": 704,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-mechoulam",
    "file": "/atlas/entries/commons/mechoulam.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "lectura-gaoni-mechoulam-aislamiento-thc",
      "documental-cannabis-medicinal"
    ],
    "sourceId": "visual-open-mechoulam",
    "author": "Panoramix303 (versión derivada); autor de la fotografía original no identificado",
    "license": "Dominio público",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Raphael_Mechoulam.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Raphael_Mechoulam.jpg",
    "alt": "Retrato de Raphael Mechoulam. Fotografía de referencia del investigador; no es un fotograma del documental ni del trabajo de 1964.",
    "caption": "Retrato de Raphael Mechoulam. Fotografía de referencia del investigador; no es un fotograma del documental ni del trabajo de 1964.",
    "credit": "Panoramix303 (versión derivada); autor de la fotografía original no identificado · Public domain · Wikimedia Commons",
    "width": 250,
    "height": 324,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-vermiculita",
    "file": "/atlas/entries/commons/vermiculita.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "componentes-de-sustrato"
    ],
    "sourceId": "visual-open-vermiculita",
    "author": "Slowshoes92",
    "license": "Dominio público",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vermiculite.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Vermiculite.jpg",
    "alt": "Vermiculita usada como componente de sustratos. Su aspecto no permite establecer la proporción adecuada para una mezcla de cultivo.",
    "caption": "Vermiculita usada como componente de sustratos. Su aspecto no permite establecer la proporción adecuada para una mezcla de cultivo.",
    "credit": "Slowshoes92 · Public domain · Wikimedia Commons",
    "width": 500,
    "height": 332,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-canamo-campo",
    "file": "/atlas/entries/commons/canamo-campo.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "industria-cannabis-argentina-actual",
      "noticia-ariccame-canamo-horticola"
    ],
    "sourceId": "visual-open-canamo-campo",
    "author": "Kifcure",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hemp-field-1080x720.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/7/76/Hemp-field-1080x720.jpg",
    "alt": "Campo de cáñamo industrial en Maple Park, Illinois, Estados Unidos. Imagen de referencia del cultivo; no documenta producción en Argentina.",
    "caption": "Campo de cáñamo industrial en Maple Park, Illinois, Estados Unidos. Imagen de referencia del cultivo; no documenta producción en Argentina.",
    "credit": "Kifcure · CC0 · Wikimedia Commons",
    "width": 500,
    "height": 333,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-dominancia-apical",
    "file": "/atlas/entries/commons/dominancia-apical.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "entrenamiento-de-bajo-estres-lst",
      "fim"
    ],
    "sourceId": "visual-open-dominancia-apical",
    "author": "Sten Porse",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Apical-dominance.png",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Apical-dominance.png",
    "alt": "Dominancia apical: ubicación de las yemas y relación entre el ápice y la ramificación. Esquema general del mecanismo vegetal, no una secuencia de ejecución de LST o FIM.",
    "caption": "Dominancia apical: ubicación de las yemas y relación entre el ápice y la ramificación. Esquema general del mecanismo vegetal, no una secuencia de ejecución de LST o FIM.",
    "credit": "Sten Porse · CC BY-SA 3.0 · Wikimedia Commons",
    "width": 500,
    "height": 708,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-oms",
    "file": "/atlas/entries/commons/oms.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "lectura-oms-informe-critico-cannabis"
    ],
    "sourceId": "visual-open-oms",
    "author": "TMorata",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:WHO_Headquarter_in_Geneva.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/0/01/WHO_Headquarter_in_Geneva.jpg",
    "alt": "Sede de la Organización Mundial de la Salud en Ginebra. Fotografía de la institución que publicó el informe reseñado.",
    "caption": "Sede de la Organización Mundial de la Salud en Ginebra. Fotografía de la institución que publicó el informe reseñado.",
    "credit": "TMorata · CC BY 4.0 · Wikimedia Commons",
    "width": 1125,
    "height": 1500,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-termometro",
    "file": "/atlas/entries/commons/termometro.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "temperatura-y-desarrollo"
    ],
    "sourceId": "visual-open-termometro",
    "author": "user:Uwe W.",
    "license": "Dominio público",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Minimum-Maximum_Thermometer.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/5/54/Minimum-Maximum_Thermometer.jpg",
    "alt": "Termómetro de máxima y mínima: instrumento para registrar el rango de temperatura ambiental.",
    "caption": "Termómetro de máxima y mínima: instrumento para registrar el rango de temperatura ambiental.",
    "credit": "user:Uwe W. · Public domain · Wikimedia Commons",
    "width": 500,
    "height": 1120,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-dewey-1910",
    "file": "/atlas/entries/commons/dewey-1910.webp",
    "type": "illustration",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "lectura-dewey-1910-cultivo-canamo-usda"
    ],
    "sourceId": "visual-open-dewey-1910",
    "author": "Dewey, Lyster H. (Lyster Hoxie), 1865-1944 United States. Bureau of Plant Industry",
    "license": "Dominio público",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_cultivation_of_hemp_in_the_United_States_(IA_cultivationofhem57dewe).pdf",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/The_cultivation_of_hemp_in_the_United_States_%28IA_cultivationofhem57dewe%29.pdf",
    "alt": "Portada original de The Cultivation of Hemp in the United States, de Lyster H. Dewey, publicada por el USDA en 1910.",
    "caption": "Portada original de The Cultivation of Hemp in the United States, de Lyster H. Dewey, publicada por el USDA en 1910.",
    "credit": "Dewey, Lyster H. (Lyster Hoxie), 1865-1944 United States. Bureau of Plant Industry · Public domain · Wikimedia Commons",
    "width": 951,
    "height": 1500,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Portada del documento (página 3 del PDF), rasterizada y optimizada a WebP, sin recorte."
  },
  {
    "id": "asset-open-senescencia-vid",
    "file": "/atlas/entries/commons/senescencia-vid.webp",
    "type": "diagram",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "senescencia-y-final-del-desarrollo"
    ],
    "sourceId": "visual-open-senescencia-vid",
    "author": "Cristina Ruberti, Elisabetta Barizza, Martina Bodner, Nicoletta La Rocca, Roberto De Michele, Francesco Carimi, Fiorella Lo Schiavo y Michela Zottini",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "sourceUrl": "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0102012",
    "originalUrl": "https://journals.plos.org/plosone/article/figure/image?id=10.1371%2Fjournal.pone.0102012.g001&size=large",
    "alt": "Senescencia de hojas de vid (Vitis vinifera): el panel A muestra el cambio de color y el panel B la pérdida de clorofila. Figura 1 de Ruberti y colaboradores (2014); ejemplo de fisiología vegetal general, no de Cannabis.",
    "caption": "Senescencia de hojas de vid (Vitis vinifera): el panel A muestra el cambio de color y el panel B la pérdida de clorofila. Figura 1 de Ruberti y colaboradores (2014); ejemplo de fisiología vegetal general, no de Cannabis.",
    "credit": "Cristina Ruberti, Elisabetta Barizza, Martina Bodner, Nicoletta La Rocca, Roberto De Michele, Francesco Carimi, Fiorella Lo Schiavo y Michela Zottini · CC BY 4.0 · PLOS ONE",
    "width": 1600,
    "height": 1793,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  },
  {
    "id": "asset-open-frasco",
    "file": "/atlas/entries/commons/frasco.webp",
    "type": "photo",
    "categoryId": null,
    "entryId": null,
    "entryIds": [
      "almacenamiento"
    ],
    "sourceId": "visual-open-frasco",
    "author": "Autor no identificado en la ficha original",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jar,_preserving_(AM_616706).jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/5/56/Jar%2C_preserving_%28AM_616706%29.jpg",
    "alt": "Frasco de vidrio con tapa, conservado en el Auckland Museum. Imagen de referencia de un recipiente de almacenamiento.",
    "caption": "Frasco de vidrio con tapa, conservado en el Auckland Museum. Imagen de referencia de un recipiente de almacenamiento.",
    "credit": "Autor no identificado · CC BY 4.0 · Wikimedia Commons",
    "width": 1125,
    "height": 1500,
    "status": "ACTIVE",
    "knownIssues": null,
    "verifiedAt": "2026-10-06",
    "modifications": "Conversión a WebP y ajuste de tamaño, sin recorte."
  }
];
